#include "logging.h"

Q_LOGGING_CATEGORY(NETWORK_REPLY, "network.reply")
Q_LOGGING_CATEGORY(NETWORK_REPLY_DATA, "network.reply.data")
Q_LOGGING_CATEGORY(NETWORK_SESSION, "nework.session")
Q_LOGGING_CATEGORY(NETWORK_SESSION_DATA, "network.session.data")
Q_LOGGING_CATEGORY(JIRA_INTERNAL, "jira.internal")
Q_LOGGING_CATEGORY(JIRA_API, "jira.api")
Q_LOGGING_CATEGORY(JIRA_API_DATA, "jira.api.data")
Q_LOGGING_CATEGORY(RESOURCES, "jira.resources")
